name: Node.js CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
       run:
         working-directory: ./vue

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3.8'
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        cd ../laravel
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        composer install
        php artisan key:generate
        chmod -R 775 storage bootstrap/cache
        mkdir -p database
        touch database/database.sqlite
        php artisan serve &
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './vue/package-lock.json'
    - name: Execute tests
      run: |
        npm ci
        npm run test:e2e:ci
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ../laravel/database/database.sqlite