name: Node.js CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
       run:
         working-directory: ./vue

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './vue/package-lock.json'
    - name: PHP dependencies install
      run: |
        apt-get update -y
        apt-get install -y php-sqlite3 phpunit unzip curl
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
    - name: Launched Laravel
      run: |
        cd ../laravel
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
        chmod -R 775 storage bootstrap/cache
    - name: Create Database
      run: |
        cd ../laravel
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests
      run: |
        npm ci
        npm run build --if-present
        npm test